// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBc2bKPbm86ULk6A1t6IM-EGIDHfHj98iI',
    appId: '1:752461189990:web:31747cbff280e4815c6ea7',
    messagingSenderId: '752461189990',
    projectId: 'deeplearningappproject',
    authDomain: 'deeplearningappproject.firebaseapp.com',
    storageBucket: 'deeplearningappproject.firebasestorage.app',
    measurementId: 'G-TWHNKY3R94',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD39iqtvdabFrHO9A-9awKSbfVttxPdnK0',
    appId: '1:752461189990:android:8f318fd2e1acd99a5c6ea7',
    messagingSenderId: '752461189990',
    projectId: 'deeplearningappproject',
    storageBucket: 'deeplearningappproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMuOlImkghbwFAr55aU9nv38WnoJ4eGpw',
    appId: '1:752461189990:ios:9e5c3d9cea06c8f55c6ea7',
    messagingSenderId: '752461189990',
    projectId: 'deeplearningappproject',
    storageBucket: 'deeplearningappproject.firebasestorage.app',
    iosBundleId: 'com.cjh.flutterWorkspace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMuOlImkghbwFAr55aU9nv38WnoJ4eGpw',
    appId: '1:752461189990:ios:9e5c3d9cea06c8f55c6ea7',
    messagingSenderId: '752461189990',
    projectId: 'deeplearningappproject',
    storageBucket: 'deeplearningappproject.firebasestorage.app',
    iosBundleId: 'com.cjh.flutterWorkspace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBc2bKPbm86ULk6A1t6IM-EGIDHfHj98iI',
    appId: '1:752461189990:web:5bd1ad4a3c89ddde5c6ea7',
    messagingSenderId: '752461189990',
    projectId: 'deeplearningappproject',
    authDomain: 'deeplearningappproject.firebaseapp.com',
    storageBucket: 'deeplearningappproject.firebasestorage.app',
    measurementId: 'G-DPVJ7WD01T',
  );
}
